github: [oshkoshbagoshh]


stripe: [stripe_link_here.html]

# patreon: yourusername
# open_collective: project-name
# ko_fi: yourusername
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: yourusername
# issuehunt: yourusername
# otechie: yourusername
# custom: ['https://www.buymeacoffee.com/yourusername', 'https://paypal.me/yourusername', 'https://your-custom-site.com/donate']
