create table products
(
    "Video Counts"                REAL,
    URL                           TEXT,
    File                          TEXT,
    "#"                           REAL,
    "Product Name"                TEXT,
    Brand                         TEXT,
    Price                         REAL,
    "Price 30"                    REAL,
    "Min Price"                   REAL,
    Net                           REAL,
    "FBA Fees"                    REAL,
    "Net Margin"                  REAL,
    LQS                           REAL,
    Category                      TEXT,
    "Product Score for PL"        REAL,
    "Product Score for Reselling" REAL,
    Sellers                       REAL,
    `rank`                          REAL,
    "BSR 30"                      REAL,
    Inventory                     REAL,
    "Est. Sales"                  REAL,
    "Est. Revenue"                REAL,
    "# of Reviews"                REAL,
    RPR                           REAL,
    "Available From"              TEXT,
    Rating                        REAL,
    "Best Seller in"              TEXT,
    "Best Seller Category URL"    TEXT,
    "A+"                          REAL,
    Weight                        REAL,
    "Seller Type"                 TEXT,
    Variants                      REAL,
    ASIN                          TEXT,
    Timestamp                     TEXT
);


